#!/usr/bin/env python3
"""Generate and verify the Stage 0 vNext contract artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "services" / "laoji-api"))

from app.schemas.meeting_facts_v3 import (  # noqa: E402
    MeetingFactsDocumentV3,
    MeetingFactsModelResponseV3,
)
from app.schemas.schedule import ScheduleParseRequest, ScheduleParseResponse  # noqa: E402
from app.schemas.vnext_contracts import (  # noqa: E402
    AsrBatchRequestV2,
    AsrBatchResponseV2,
    EntityRevision,
    ProjectionEnvelope,
    RealtimeChunkHeaderV2,
    ScheduleDraft,
    ScheduleMentionGraph,
    SourceRef,
    TaskAttempt,
    TranscriptStreamEventV2,
    UploadSession,
)


SCHEMA_MODELS = {
    "entity_revision": EntityRevision,
    "source_ref": SourceRef,
    "task_attempt": TaskAttempt,
    "asr_batch_request_v2": AsrBatchRequestV2,
    "asr_batch_response_v2": AsrBatchResponseV2,
    "transcript_stream_event_v2": TranscriptStreamEventV2,
    "realtime_chunk_header_v2": RealtimeChunkHeaderV2,
    "upload_session": UploadSession,
    "projection_envelope": ProjectionEnvelope,
    "schedule_mention_graph": ScheduleMentionGraph,
    "schedule_draft": ScheduleDraft,
    "schedule_parse_request_legacy_projection": ScheduleParseRequest,
    "schedule_parse_response_legacy_projection": ScheduleParseResponse,
    "meeting_facts_model_response_v3": MeetingFactsModelResponseV3,
    "meeting_facts_document_v3": MeetingFactsDocumentV3,
}


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=True, sort_keys=True, indent=2) + "\n"


def render() -> tuple[dict[str, str], str, str, str]:
    schemas = {
        name: canonical_json(model.model_json_schema())
        for name, model in sorted(SCHEMA_MODELS.items())
    }
    manifest = {
        "contract_revision": "vnext-1",
        "schema_source": "services/laoji-api/app/schemas",
        "schemas": [
            {
                "name": name,
                "path": f"schemas/{name}.schema.json",
                "sha256": hashlib.sha256(content.encode()).hexdigest(),
            }
            for name, content in sorted(schemas.items())
        ],
    }
    manifest_text = canonical_json(manifest)
    names = ",\n".join(
        f"  {json.dumps(item['name'])}: {json.dumps(item['sha256'])}"
        for item in manifest["schemas"]
    )
    typescript = (
        "// Generated by contracts/vnext/generate.py; do not edit.\n"
        "export const VNEXT_CONTRACT_REVISION = 'vnext-1' as const;\n"
        "export const VNEXT_SCHEMA_SHA256 = {\n"
        f"{names}\n"
        "} as const;\n"
        "export type VNextSchemaName = keyof typeof VNEXT_SCHEMA_SHA256;\n"
    )
    kotlin_entries = ",\n".join(
        f"        {json.dumps(item['name'])} to {json.dumps(item['sha256'])}"
        for item in manifest["schemas"]
    )
    kotlin = (
        "// Generated by contracts/vnext/generate.py; do not edit.\n"
        "package com.laoji.contracts\n\n"
        "object VNextSchemaManifest {\n"
        '    const val CONTRACT_REVISION: String = "vnext-1"\n'
        "    val SHA256: Map<String, String> = mapOf(\n"
        f"{kotlin_entries}\n"
        "    )\n"
        "}\n"
    )
    return schemas, manifest_text, typescript, kotlin


def expected_files() -> dict[Path, str]:
    schemas, manifest, typescript, kotlin = render()
    result = {ROOT / "contracts/vnext/generated/manifest.json": manifest}
    result[ROOT / "contracts/vnext/generated/index.ts"] = typescript
    result[ROOT / "contracts/vnext/generated/SchemaManifest.kt"] = kotlin
    for name, content in schemas.items():
        result[ROOT / f"contracts/vnext/generated/schemas/{name}.schema.json"] = content
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = expected_files()
    mismatches: list[str] = []
    for path, content in files.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                mismatches.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if mismatches:
        print("contract_artifacts_out_of_date")
        print("\n".join(mismatches))
        return 1
    print(f"contract_artifacts={'verified' if args.check else 'generated'} count={len(files)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
